services:
  php-app:
    image: kirytosao/parcial2:3.0
    container_name: parcial-php-app
    ports:
      - "8080:80"
    environment:
      DB_HOST: mysql
      DB_NAME: parcial_db
      DB_USER: root
      DB_PASSWORD: rootpassword
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - parcial-network
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    container_name: parcial-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: parcial_db
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - parcial-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-prootpassword"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  mysql-data:
    driver: local

networks:
  parcial-network:
    driver: bridge
